version: '3'
services:
  mysql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-users:/docker-entrypoint-initdb.d/
  server-users:
    build: ./server-users
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=81
      - MYSQLHOST=mysql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=kn24
      - TOTP=2025
      - JWTSECRET=jwtsupersecretcode
    volumes:
      - ./server-users/backend:/app/backend
    ports:
      - "8001:80"
  mysql-website:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-website:/docker-entrypoint-initdb.d/
  server-website:
    build: ./server-website
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=authdb
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server-website/backend:/app/backend
      - ./server-website/frontend:/app/frontend
    ports:
      - "80:80"
