version: '3'
services:
  datadb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/sludge:/docker-entrypoint-initdb.d/
  authdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/auth:/docker-entrypoint-initdb.d/
  auth_server:
    build: ./auth_server
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=authdb
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=kn24
      - JWTSECRET= jwtsupersecretpassword
      - TOTP=2025
    volumes:
      - ./auth_server/backend:/app/backend
      - ./auth_server/frontend:/app/frontend
    ports:
      - "80:80"
  sludge_server:
    build: ./sludge_server
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=81
      - MYSQLHOST=datadb
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./sludge_server/backend:/app/backend
    ports:
      - "81:81"
