version: '3'
services:
  datadb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/sql-website:/docker-entrypoint-initdb.d/
  authdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/sql-users:/docker-entrypoint-initdb.d/
  server-website:
    build: ./server-website
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=datadb
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server-website/backend-website:/app/backend
      - ./server-website/frontend:/app/frontend
    ports:
      - "80:80"
  server-users:
    build: ./server-users
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=authdb
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=kn24
      - JWTSECRET= jwtsupersecretpassword
      - TOTP=2025
    volumes:
      - ./server-users/backend:/app/backend
    ports:
      - "8001:80"
